export const sampleSystemUsers = [
  {
    id: '1',
    id_no: '1001',
    username: 'ahmad.natsheh',
    email: 'ahmad.natsheh@kendo.ps',
    first_name: 'Ahmad',
    second_name: 'Yousef',
    third_name: 'Omar',
    last_name: 'Natsheh',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599111111',
    address: 'Hebron',
    status: 'active' as const,
  },
  {
    id: '2',
    id_no: '1002',
    username: 'fatima.salem',
    email: 'fatima.salem@kendo.ps',
    first_name: 'Fatima',
    second_name: 'Ali',
    third_name: 'Hassan',
    last_name: 'Salem',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599222222',
    address: 'Ramallah',
    status: 'active' as const,
  },
  {
    id: '3',
    id_no: '1003',
    username: 'mohammad.abdullah',
    email: 'mohammad.abdullah@kendo.ps',
    first_name: 'Mohammad',
    second_name: 'Khaled',
    third_name: 'Sami',
    last_name: 'Abdullah',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599333333',
    address: 'Nablus',
    status: 'active' as const,
  },
  {
    id: '4',
    id_no: '1004',
    username: 'sara.hijazi',
    email: 'sara.hijazi@kendo.ps',
    first_name: 'Sara',
    second_name: 'Mahmoud',
    third_name: 'Fadi',
    last_name: 'Hijazi',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599444444',
    address: 'Jenin',
    status: 'active' as const,
  },
  {
    id: '5',
    id_no: '1005',
    username: 'yousef.odeh',
    email: 'yousef.odeh@kendo.ps',
    first_name: 'Yousef',
    second_name: 'Suleiman',
    third_name: 'Nabil',
    last_name: 'Odeh',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599555555',
    address: 'Tulkarm',
    status: 'active' as const,
  },
  {
    id: '6',
    id_no: '1006',
    username: 'mona.khalil',
    email: 'mona.khalil@kendo.ps',
    first_name: 'Mona',
    second_name: 'Hani',
    third_name: 'Rami',
    last_name: 'Khalil',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599666666',
    address: 'Qalqilya',
    status: 'active' as const,
  },
  {
    id: '7',
    id_no: '1007',
    username: 'hassan.abuzaid',
    email: 'hassan.abuzaid@kendo.ps',
    first_name: 'Hassan',
    second_name: 'Fares',
    third_name: 'Adel',
    last_name: 'AbuZaid',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599777777',
    address: 'Jericho',
    status: 'active' as const,
  },
  {
    id: '8',
    id_no: '1008',
    username: 'dina.sabbagh',
    email: 'dina.sabbagh@kendo.ps',
    first_name: 'Dina',
    second_name: 'Rashid',
    third_name: 'Amin',
    last_name: 'Sabbagh',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599888888',
    address: 'Bethlehem',
    status: 'active' as const,
  },
  {
    id: '9',
    id_no: '1009',
    username: 'khaled.ahmad',
    email: 'khaled.ahmad@kendo.ps',
    first_name: 'Khaled',
    second_name: 'Sami',
    third_name: 'Fouad',
    last_name: 'Ahmad',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599999999',
    address: 'Salfit',
    status: 'active' as const,
  },
  {
    id: '10',
    id_no: '1010',
    username: 'layla.hassan',
    email: 'layla.hassan@kendo.ps',
    first_name: 'Layla',
    second_name: 'Nasser',
    third_name: 'Jamal',
    last_name: 'Hassan',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599101010',
    address: 'Tubas',
    status: 'active' as const,
  },
  {
    id: '11',
    id_no: '1011',
    username: 'ibrahim.salem',
    email: 'ibrahim.salem@kendo.ps',
    first_name: 'Ibrahim',
    second_name: 'Yasin',
    third_name: 'Majed',
    last_name: 'Salem',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599111112',
    address: 'Hebron',
    status: 'active' as const,
  },
  {
    id: '12',
    id_no: '1012',
    username: 'amal.abuzaid',
    email: 'amal.abuzaid@kendo.ps',
    first_name: 'Amal',
    second_name: 'Fadi',
    third_name: 'Rami',
    last_name: 'AbuZaid',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599121212',
    address: 'Jericho',
    status: 'active' as const,
  },
  {
    id: '13',
    id_no: '1013',
    username: 'samir.haddad',
    email: 'samir.haddad@kendo.ps',
    first_name: 'Samir',
    second_name: 'Nabil',
    third_name: 'Hani',
    last_name: 'Haddad',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599131313',
    address: 'Qalqilya',
    status: 'active' as const,
  },
  {
    id: '14',
    id_no: '1014',
    username: 'ruba.samir',
    email: 'ruba.samir@kendo.ps',
    first_name: 'Ruba',
    second_name: 'Sami',
    third_name: 'Fares',
    last_name: 'Samir',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599141414',
    address: 'Nablus',
    status: 'active' as const,
  },
  {
    id: '15',
    id_no: '1015',
    username: 'fadi.odeh',
    email: 'fadi.odeh@kendo.ps',
    first_name: 'Fadi',
    second_name: 'Khalil',
    third_name: 'Yousef',
    last_name: 'Odeh',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599151515',
    address: 'Tulkarm',
    status: 'active' as const,
  },
  {
    id: '16',
    id_no: '1016',
    username: 'salma.abdullah',
    email: 'salma.abdullah@kendo.ps',
    first_name: 'Salma',
    second_name: 'Hassan',
    third_name: 'Ali',
    last_name: 'Abdullah',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599161616',
    address: 'Ramallah',
    status: 'active' as const,
  },
  {
    id: '17',
    id_no: '1017',
    username: 'adel.hijazi',
    email: 'adel.hijazi@kendo.ps',
    first_name: 'Adel',
    second_name: 'Mahmoud',
    third_name: 'Fadi',
    last_name: 'Hijazi',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599171717',
    address: 'Jenin',
    status: 'active' as const,
  },
  {
    id: '18',
    id_no: '1018',
    username: 'nour.sabbagh',
    email: 'nour.sabbagh@kendo.ps',
    first_name: 'Nour',
    second_name: 'Rashid',
    third_name: 'Amin',
    last_name: 'Sabbagh',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599181818',
    address: 'Bethlehem',
    status: 'active' as const,
  },
  {
    id: '19',
    id_no: '1019',
    username: 'jamal.khalil',
    email: 'jamal.khalil@kendo.ps',
    first_name: 'Jamal',
    second_name: 'Hani',
    third_name: 'Rami',
    last_name: 'Khalil',
    gender: 'male' as const,
    password: 'password123',
    phone_number: '+970599191919',
    address: 'Qalqilya',
    status: 'active' as const,
  },
  {
    id: '20',
    id_no: '1020',
    username: 'yasmin.ahmad',
    email: 'yasmin.ahmad@kendo.ps',
    first_name: 'Yasmin',
    second_name: 'Sami',
    third_name: 'Fouad',
    last_name: 'Ahmad',
    gender: 'female' as const,
    password: 'password123',
    phone_number: '+970599202020',
    address: 'Salfit',
    status: 'active' as const,
  },
]; 